# Generated by Django 5.2.3 on 2025-06-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saveditem',
            options={'verbose_name': 'Saved Item', 'verbose_name_plural': 'Saved Items'},
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='items.category'),
        ),
    ]
